### ISSUE TITLE
'The service "pathauto.generator" has a dependency on a non-existent service "token.entity_mapper"

### ISSUE THREAD

**Issue by njt1982** [md-systems/pathauto#122]
Any idea's?

Using token 1.0-alpha1 and ctools 3.0-alpha20. Using 3370284268cc1df0a65b0dae2ce0d95c70779dc7 of pathauto.

```
$ drush cr
exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'The service "pathauto.generator" has a dependency on a non-existent service "token.entity_mapper".' in /Users/nthompson/Sites/CLIENT/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:58
Stack trace:
#0 /Users/nthompson/Sites/CLIENT/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(42):
Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processReferences(Array)
#1 /Users/nthompson/Sites/CLIENT/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(36):
Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processDefinition(Object(Symfony\Component\DependencyInjection\Definition))
#2 /Users/nthompson/Sites/CLIENT/vendor/symfony/dependency-injection/Compiler/Compiler.php(107):
Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->process(Object(Drupal\Core\DependencyInjection\ContainerBuilder))
#3 /Users/nthompson/Sites/CLIENT/vendor/symfony/dependency-injection/ContainerBuilder.php(570):
Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Drupal\Core\DependencyInjection\ContainerBuilder))
#4 /Users/nthompson/Sites/CLIENT/web/core/lib/Drupal/Core/DrupalKernel.php(1198): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#5 /Users/nthompson/Sites/CLIENT/web/core/lib/Drupal/Core/DrupalKernel.php(824): Drupal\Core\DrupalKernel->compileContainer()
#6 /Users/nthompson/Sites/CLIENT/web/core/lib/Drupal/Core/DrupalKernel.php(441): Drupal\Core\DrupalKernel->initializeContainer()
#7 /Users/nthompson/Sites/CLIENT/web/core/lib/Drupal/Core/DrupalKernel.php(686): Drupal\Core\DrupalKernel->boot()
#8 /Users/nthompson/Sites/CLIENT/web/core/includes/utility.inc(42): Drupal\Core\DrupalKernel->prepareLegacyRequest(Object(Symfony\Component\HttpFoundation\Request))
#9 /Users/nthompson/Sites/CLIENT/vendor/drush/drush/commands/core/cache.drush.inc(291): drupal_rebuild(Object(Composer\Autoload\ClassLoader),
Object(Symfony\Component\HttpFoundation\Request))
#10 [internal function]: drush_cache_rebuild()
#11 /Users/nthompson/Sites/CLIENT/vendor/drush/drush/includes/command.inc(366): call_user_func_array('drush_cache_reb...', Array)
#12 /Users/nthompson/Sites/CLIENT/vendor/drush/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#13 [internal function]: drush_command()
#14 /Users/nthompson/Sites/CLIENT/vendor/drush/drush/includes/command.inc(185): call_user_func_array('drush_command', Array)
#15 /Users/nthompson/Sites/CLIENT/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#16 /Users/nthompson/Sites/CLIENT/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#17 /Users/nthompson/Sites/CLIENT/vendor/drush/drush/drush.php(12): drush_main()
#18 {main}
```

**Comment by Berdir** [comment]
Yes, I have an idea :)

 Use the latest dev snapshots of both those modules, the alphas don't work.

**Comment by njt1982** [comment]
Thanks. Might be worth mentioning that on the project front page 😉

**Comment by njt1982** [comment]
Yup - that solved it.
